import "./App.js";
import { p as pushScopeId, b as popScopeId } from "./vendor.js";
import "./App2.js";
/* empty css     */import "./logo.js";
var CenterTitle_vue_vue_type_style_index_0_scoped_true_lang = "\na[data-v-39aeb044] {\n  color: #42b983;\n}\n*[data-v-39aeb044] {\n    box-sizing: content-box;\n    line-height : normal;\n}\np[data-v-39aeb044] {\n    display: block;\n    margin-block-start: 1em;\n    margin-block-end: 1em;\n    margin-inline-start: 0px;\n    margin-inline-end: 0px;\n}\nh1[data-v-39aeb044] {\n    display: block;\n    font-size: 2em;\n    margin-block-start: 0.67em;\n    margin-block-end: 0.67em;\n    margin-inline-start: 0px;\n    margin-inline-end: 0px;\n    font-weight: bold;\n}\nbutton[data-v-39aeb044] {\n    /* width: 100px;\n    height: 30px; */\n    appearance: auto;\n    -webkit-writing-mode: horizontal-tb !important;\n    text-rendering: auto;\n    color: -internal-light-dark(black, white);\n    letter-spacing: normal;\n    word-spacing: normal;\n    text-transform: none;\n    text-indent: 0px;\n    text-shadow: none;\n    display: inline-block;\n    text-align: center;\n    align-items: flex-start;\n    cursor: default;\n    background-color: -internal-light-dark(rgb(239, 239, 239), rgb(59, 59, 59));\n    box-sizing: border-box;\n    margin: 0em;\n    font: 400 13.3333px Arial;\n    padding: 1px 6px;\n    border-width: 2px;\n    border-style: outset;\n    border-color: -internal-light-dark(rgb(118, 118, 118), rgb(133, 133, 133));\n    border-image: initial;\n    border-radius: 2px;\n}\n\n";
var room = "/* Now, our styles */\n\n#room {\n    font-family: Avenir, Helvetica, Arial, sans-serif;\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n    text-align: center;\n    color: #f2e6e5;\n    margin: 30px;\n    border: 5px;\n    border-radius: 10px;\n    border-color: red;\n    position: absolute;\n    display: block;\n    background-color: black;\n  }\n\n  #room .spacer {\n    margin-left: 25px;\n    margin-right: 25px;\n    }\n\n  #room .squareoff {\n    text-align: justify;\n    }\n  ";
var App_vue_vue_type_style_index_0_scoped_true_lang$e = "\n\n";
pushScopeId("data-v-3ec6c432");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$d = "\n\n";
pushScopeId("data-v-8bbf9448");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$c = "\n\n";
pushScopeId("data-v-2f8a1568");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$b = "\n\n";
pushScopeId("data-v-48533ae5");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$a = "\n\n";
pushScopeId("data-v-62245168");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$9 = "\n\n";
pushScopeId("data-v-88d0b02e");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$8 = "\n\n";
pushScopeId("data-v-17011da7");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$7 = "\n\n";
pushScopeId("data-v-e88e8c04");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$6 = "\n\n";
pushScopeId("data-v-72718009");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$5 = "\n\n";
pushScopeId("data-v-aadf164e");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$4 = "\n\n";
pushScopeId("data-v-28844930");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$3 = "\n\n";
pushScopeId("data-v-bb3eadc6");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$2 = "\n\n";
pushScopeId("data-v-4ea20f04");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang$1 = "\n\n";
pushScopeId("data-v-641fb642");
popScopeId();
var App_vue_vue_type_style_index_0_scoped_true_lang = "\n\n";
pushScopeId("data-v-c4d0e768");
popScopeId();
